### ISSUE TITLE
什么时候会公开源码？

### ISSUE THREAD

**Issue by WangliLin** [zhaoyizhaoyi/hm-densernns#1]

**Comment by zhaoyizhaoyi** [comment]
Thanks for your attention. Currently I am busying working on my thesis paper and experiments. Because the original project is kind of messy, it will take some time to clean and sort out. Sorry for the delay. I will do this job once I finish my work on thesis paper. That is said, I would try to release the code before the end of January.

**Comment by guotong1988** [comment]
Same Question.

**Comment by zhaoyizhaoyi** [comment]
Sorry for the dealy. I have create a new dev branch. Code for the dense rnn model has been uploaded. Running scripts, configurations and pretrained models would be uploaded soon.
